- name: install files
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present  
      enabled: yes 

