- name: multi play
  hosts: local
  connection: local
  vars: # this play variables are print total playbook
    COURSE: "ANSIBLE"
    DURATION: "120 HRS"
  tasks:
  - name: variable
    vars: # in task variables only print in this task only
      COURSE: "Devops"
      DURATION: "120 Hrs"
    ansible.builtin.debug:
     msg: "hello {{ COURSE }}, This course duration is {{ DURATION }}"

  - name: print variables
    ansible.builtin.debug:
      msg: " hello {{ COURSE }}, this course duration is {{ DURATION }}"



