- name: multi play
  hosts: local
  connection: local
  vars:
    ALL: "ANSIBLE"
    WELCOME: "120 HRS"
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
     msg: "hello {{ COURSE }}, This course duration is {{ DURATION }}"